import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import Item from "../components/Item"
import ItemForm from "../components/ItemForm"
import Modal from "../components/Modal"
import ThemeChanger from "../components/ThemeChanger"
import styles from "./styles.module.scss"

export default function Home() {
  const addButton = useRef()
  const [list, setList] = useState([])
  const [showModal, setShowModal] = useState(false)

  useEffect(() => {
    const data = window.localStorage.getItem("marketlist-tydrok")
    if (data) setList(JSON.parse(data))
  }, [])
  useEffect(() => {
    if (addButton.current) addButton.current.focus()
  }, [showModal])

  return (
    <div className={styles.background}>
      <Head>
        <title>Marketlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeChanger />
      <main className={styles.view}>
        <h1 className={styles.title}>Supermarket list</h1>
        <h2 className={styles.counter}>{list.length} item(s)</h2>
        <ul className={styles.list}>
          {list.map((e) => (
            <Item data={e} key={e.id} listState={[list, setList]} />
          ))}
        </ul>
        {showModal ? (
          <Modal>
            <ItemForm setShowModal={setShowModal} listState={[list, setList]} />
          </Modal>
        ) : (
          <button
            onClick={() => setShowModal(true)}
            className={styles.button}
            ref={addButton}
          >
            Add item
          </button>
        )}
      </main>
    </div>
  )
}
